### ISSUE TITLE
Still functional? If so which tricks are use to get access?

### ISSUE THREAD

**Issue by Osiris-Team** [amacado/handelsregister-cli#6]
Hey @amacado is your tool still functional even though the handlesregister website always returns 403 even in the regular browser?

If its functional do you mind explaining which tricks are used to bypass this, since I need to implement a client for this "API" in Java. Would greatly appreciate the help!

**Comment by amacado** [comment]
@Osiris-Team I would wonder if the cli works when the Handelsregister website responds with 403 error because the cli is basically just executing steps through chrome browser.

Looks there there is currently a ongoing problem at handelsregister.de. As mentioned in the readme I'm not related nor responsible for the Handelsregister service at all.

**Comment by Osiris-Team** [comment]
Okay, thanks good to know!
Was wondering if a login or something is required because of the 403 error.
Guess its just something wrong on their end then...

**Comment by amacado** [comment]
Some maintenance works seems to be confirmed:

![image](https://github.com/user-attachments/assets/2fb2c202-ba7c-42d8-886e-cc6673542a6b)

**Comment by Osiris-Team** [comment]
thats probably it, thanks!
